* Unix, Windows and DotNet 

Bash as REPL, an interactive programming environment

Everything is a file in a tree
  - including things like `/dev/random`, `/dev/zero`
	- but also process and thread memory - os resources you'd expect to be hidden away below many layers
	- hierarchy from machine to person to sub-interest: devices and core unix tools at top, then gradations downwards
		
TREES on TREES
  - file tree as view of sub-system, sub-computer
  - a primitive form of isolation
	- could be provided by network-mounts, from shared mainframe, etc
	- overlaid to give complete system

Variety of Unixes
  - Cygwin, WSL - Linux
	- Android! 
	- iOS
	- Mac OSX
	- POSIX standard: things that appear everywhere, even in Git Bash
		- to rein in the multiplicity of competing, branched Unixes, from late 1980s
			
Pipes
  - the Unix version of LINQ
		think LINQ where every operator has countless obscure flags
		(LINQ of course takes very nice C# lambda arguments - the DSL dream almost)
		also think a LINQ where operators might take a second or two to do things - not so transparent - less mathematical, more mechanical
			
POSIX
  - less important now with docker available
			
Windows stands alone 
  - all other popular OSes are unixes
	- genealogical tree simplified
	- though development is done in closed worlds (JVMs, CLRs and NodeJSs etc)
		- but Unix is itself such a development environment
		- in our world the development environment and the OS are more split than in others
		- Shell=REPL
  
The path to containers
  - from basic unix stuff via extensions
  - fork/exec copies executes - very similar to Docker
		- amazing Windows mimicry, v wasteful!
	- chroot
	- cgroups

Shining familiar example: Git
  - non-monolithic
  - everything is small processes
		
Shining familiar example: Docker

Setting up listeners, watchers, multiplexing
  - steps towards an build-it-yourself IDE

Tour of handy commands
  - grep
	- sed
	- awk
	- netcat
	- curl
		
Compiling from source
  - basis of portability
	- explains folder structure

Tour of file system
  - src -> lib -> bin
	- etc: config
	- var: runtime
	- root, usr, usr/local (like local/roaming appdata)
	- opt

		

*** DI and Open Source
		Dependency inversion was done via compilation of a high-level language - of C.
		This meant that source code was king: a program wasn't the machine code either hand- or machine-assembled. The compilable source code was the source of truth.
		Distribution was in source code, which was human-readable and human-tweakable.
		
		It's not that one caused the other, more a happy synergy. The hacker-centric dog-foodiness, with the everyman programmer in the middle, and the machine independence.
